### ISSUE TITLE
Better Example Project

### ISSUE THREAD

**Issue by JustAGuyAFAIK** [Grisgram/gml-commandline#1]
I was wanting to use this, but despite following the directions clearly, it doesn't work for me. Every time I would test the game, nothing would happen. I even tried testing the example project here, no debug messages popped up. I tried adding the parameters to a shortcut, nothing. I tried cmd, also nothing. I think either a better example project or better instructions would be great.

**Comment by Grisgram** [comment]
Hey there,
thanks for the hint -- I will add a small example project which will popup a message of the analyzed command line.

Then you have source code, _how_ to analyze it and you can see on screen what the game received.

**Comment by Grisgram** [comment]
https://github.com/Grisgram/gml-commandline/releases/tag/2409.1

Please make sure, to also update your local yymps - I changed some code in the lib.

**Comment by JustAGuyAFAIK** [comment]
This all works great, thank you! I think one more addition that you could add to the example use is how the switch, option, and command CMD usage is supposed to look ~~because I'm confused on how to use commands(and it is in my code to look for them).~~ Never mind, it's a "/" command. Got it working now! 

Other than that, solved!

**Comment by Grisgram** [comment]
thanks!

in short, why I seperate "switches" and "options":

especially on windows, there is no real standard. many older commands, even the built-in commands in windows use a "/", like in `dir c: /s`, but many modern command line tools would use something like `dir c: -s`. the dash symbol swapped over from the linux world and now has a second home in many windows command line tools.

and to maximize the comfort for the user, i decided to call these "switches" and it doesn't matter, if you use `-` or `/` 

an _option_, on the other hand is something, also coming from the linux world, that is mostly set through `--`, two dashes. it can't be "on" or "off", it's just there. but to distinguish them from normal switches, the double-dash is used.

it's totally up to you, which syntax you support in your app.
my library supports both. your code. your decision.

glad, the example helped you, closing this now

cheers,
Gris
